name: 1. workflow
#  workflow_dispacth (wait for user to manually start the workflow)
on: workflow_dispacth
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!" 
      - name: Print goodbye
        run: echo "Done. Bye!" 
      
